
package appsquadz;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FileDownloadImpl", targetNamespace = "http://appsquadz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileDownloadImpl {


    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://appsquadz/", className = "appsquadz.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://appsquadz/", className = "appsquadz.DownloadFileResponse")
    public byte[] downloadFile();

}
